pipeline {
    agent any
    stages {
        stage('Hello') {
          steps {
            echo 'Bonjour'
          }
        }
        stage('Build') {
            steps {
                sh 'python main/hello_world.py'
            }
        }
    }
}

